title: Tom Bond
description: Things I've made or shared over the years (including brand new silly stuff for 2024) and places you can find me
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
